### ISSUE TITLE
Send email notification upon plugin release

### ISSUE THREAD

**Issue by antoniokupresak** [pickware/scs-commander#2]
It would be very handy to notify a certain email address upon a plugin release via e-mail. The e-mail should at least contain Plugin Name, Version Number and Changelog.

**Comment by svenmuennich** [comment]
We could make the email configurable in the env file, so that it's optional.

**Comment by svenmuennich** [comment]
Closing, because since 3069e4d50c95a92dd3bd621d56f1d75f7d584e62 we support upload notifications via a configurable webhook.
