### ISSUE TITLE
Don't allow releases in the evening / on fridays

### ISSUE THREAD

**Issue by antoniokupresak** [pickware/scs-commander#9]
We just came up with the idea to block releases after a certain time in the afternoon and maybe even on fridays in general.

Of course there should be an option to override this barrier by giving a special parameter to the function (or something like that).

**Comment by fixpunkt** [comment]
We could call the flag to force a release `--yes-mom-i-know-this-is-a-bad-idea`.

**Comment by svenmuennich** [comment]
IMO this is not the responsibility of this repo at all. The `scs-commander` is a tool/library for interacting with the Shopware Community Store, not for babysitting developers.
